# Generated by Django 5.2.4 on 2025-07-26 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist_app", "0002_streamplatform_watchlist_delete_movie"),
    ]

    operations = [
        migrations.RenameField(
            model_name="watchlist",
            old_name="description",
            new_name="storyline",
        ),
        migrations.RenameField(
            model_name="watchlist",
            old_name="name",
            new_name="title",
        ),
        migrations.AddField(
            model_name="watchlist",
            name="platform",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watchlist",
                to="watchlist_app.streamplatform",
            ),
            preserve_default=False,
        ),
    ]
