# Generated by Django 5.2.4 on 2025-07-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist_app", "0004_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="description",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
